# Generated by Django 3.1.4 on 2021-02-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=20)),
                ('Course', models.CharField(max_length=20)),
                ('Semester', models.CharField(choices=[('S1', 1), ('S2', 2), ('S3', 3), ('S4', 4), ('S5', 5), ('S6', 6), ('S7', 7), ('S8', 8)], default='S1', max_length=20)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.IntegerField(unique=True)),
            ],
        ),
    ]
