# Generated by Django 3.1.4 on 2021-02-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
